name: Publish

on:
  push:
    tags:
      - v*

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: publish
          auth-token: ${{ secrets.NPM_TOKEN }}
